Enhance error reporting and handling for large JSON validations
datacontract/datacontract-cli pull request #505
Opened 2024-11-17 18:40 UTC by NiklasA

- [ ] Tests pass
- [ ] ruff format
- [ ] README.md updated (if relevant)
- [ ] CHANGELOG.md entry added

2024-11-17 20:39 UTC, NiklasA commented
@pascalrosenberger / @ManbirP could please review the PR, before I will change the status from draft to finish?

2024-11-25 10:19 UTC, hirschsebastian commented on datacontract/engines/fastjsonschema/check_jsonschema.py
> +def get_primary_key_value(schema: dict, model_name: str, json_object: dict) -> str:
Since the return value can be theoretically None, I suggest to set as a return type Optional[str].

2024-11-25 10:21 UTC, hirschsebastian commented on datacontract/engines/fastjsonschema/check_jsonschema.py
> +            )
Since we use a property `message` here, I suggest to add the property to the Check class as Optional[str].

2024-11-25 10:25 UTC, hirschsebastian requested changes
In three parts of the code I suggest adding Optional[str] to make the possibility of None more explicit.

2024-11-25 20:57 UTC, closed without merging